version: '3.9'
services:
  order-frontend:
    build:
      context: ./order-app/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - orderservice
  
      
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - inventoryservice
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - dapr-network
  
  orderservice-dapr:
    image: "daprio/daprd:1.10.0"
    command: [ 
        "./daprd", 
        "-app-id", "orderservice", 
        "-app-port",  "80",
        "--log-level", "debug",
        "-components-path", "/components",
        "-config", "/config/config.yaml"
            ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - orderservice
      - redis
      - rabbitmq
    network_mode: "service:orderservice"


  inventoryservice:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - 5001:80
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - dapr-network
    
  inventoryservice-dapr:
    image: "daprio/daprd:1.10.0"
    command: [ 
            "./daprd", 
            "-app-id", "inventoryservice",
            "-app-port", "80", 
            "--log-level", "debug",
            "-components-path", "/components",
            "-config", "/config/config.yaml"
            ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - inventoryservice
      - redis
      - rabbitmq
    network_mode: "service:inventoryservice"

  zipkin:
    container_name: "zipkin_service"
    image: "openzipkin/zipkin:2.23.4" # https://registry.hub.docker.com/r/openzipkin/zipkin
    ports:
      - 9412:9411
    networks:
      - dapr-network

  redis:
    container_name: "redis_service"
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - dapr-network

  rabbitmq:
    container_name: "rabbitmq_service"
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - dapr-network

  seq:
    image: datalust/seq:latest
    container_name: "seq_service"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seqdata:/data
    ports:
      - "5341:80"
    networks:
      - dapr-network
volumes:
   seqdata:


networks:
    dapr-network: