apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  mtls:
    enabled: false
  tracing:
    enabled: true
    exporterType: zipkin
    samplingRate: "1"
    stdout: true
    expandParams: true
    includeBody: true
    zipkin:
        endpointAddress: "http://zipkin_service:9411/api/v2/spans"
  logging:
    apiLogging:
        enabled: true
  metric:
   enabled: true
    